apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
data:
  "app-config-rhdh.yaml": |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://backstage-developer-hub-rhdh-operator.apps.mays-demo.sandbox1875.opentlc.com
    backend:
      auth:
        keys:
          - secret: secrets-rhdh
      baseUrl: https://backstage-developer-hub-rhdh-operator.apps.mays-demo.sandbox1875.opentlc.com
      cors:
        origin: https://backstage-developer-hub-rhdh-operator.apps.mays-demo.sandbox1875.opentlc.com